### ISSUE TITLE
Error with magicsunday's Fan Chart in v2.1.3-dev

### ISSUE THREAD

**Issue by stc4000** [JustCarmen/webtrees-theme-justlight#104]
Rico Sonntag's [Fan Chart](https://github.com/magicsunday/webtrees-fan-chart) (v2.2.2) is working well with any other theme. But this error occurs with the JustLight theme:

[Fan Chart in JustLight.txt](https://github.com/JustCarmen/webtrees-theme-justlight/files/8291259/Fan.Chart.in.JustLight.txt)

I'm on webtrees v2.0.22, PHP v7.2.34

**Comment by JustCarmen** [comment]
I think you are not using [the latest stable version](https://github.com/JustCarmen/webtrees-theme-justlight/releases/tag/2.1.2.3) of the JustLight theme or that you are using a mix of old and new files.

Please delete all the theme files and then upload the latest stable version to see if it solve your problem.

**Comment by stc4000** [comment]
> Please delete all the theme files and then upload the latest stable version to see if it solves your problem.

v2.1.2.3 did indeed solve the problem. Thanks a lot.
