### ISSUE TITLE
Webtrees 2.1

### ISSUE THREAD

**Issue by wp4711** [JustCarmen/webtrees-theme-justlight#107]
Is it possible to make the theme work on webtrees 2.1? (justlight theme, research links, image bar)
I like this modules and would like to use them in webtrees 2.1

**Comment by JustCarmen** [comment]
I noticed that webtrees 2.1. has reached its stable status, so I will update the theme. However, it may take some time.

**Comment by wp4711** [comment]
ok thanks for that

**Comment by JustCarmen** [comment]
Just released a new version which is compatible with webtrees 2.1.

https://github.com/JustCarmen/webtrees-theme-justlight/releases/tag/2.2.0
