### ISSUE TITLE
'Customize this page' /'MyPage': Deleting blocks is not so simple when Justlight-theme is active

### ISSUE THREAD

**Issue by ungeahnt** [JustCarmen/webtrees-theme-justlight#109]
... when I switch to webtrees standard theme deletion is possible.

[edit] justlight theme V2.2.0 and wt 2.1.2

**Comment by JustCarmen** [comment]
This is probably not a problem with the Justlight theme. See: https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/36858-customise-home-page-and-my-page-unable-to-delete-blocks-in-certain-themes

**Comment by ungeahnt** [comment]
I see the same behaviour with FAB too.

**Comment by ungeahnt** [comment]
Bitmap-Icons?

**Comment by ungeahnt** [comment]
[> fisharebest: No, I mean a small change in the javascript is required. ](https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/36858-customise-home-page-and-my-page-unable-to-delete-blocks-in-certain-themes#91616)

I still don't get it: should this be fixed in wt or in the justlight-, FAB-, .... theme?

**Comment by JustCarmen** [comment]
It is fixed with this commit in webtrees:

https://github.com/fisharebest/webtrees/commit/8b993e2f89104b0ad550bad4ad93a0b7e45f47a2

Wait for the next release or copy the changed file to your server to use it immediately.
