### ISSUE TITLE
Formatting of notes not correct

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/webtrees-theme-justlight#111]
In webtrees v2.1.2 and webtrees-theme-justlight v2.2.0 notes are displayed differently. For multi-line notes there is only a line break after "Note:", for single-line notes there is a line break after "Note" and ":". 

<img width="1419" alt="display_of_notes" src="https://user-images.githubusercontent.com/16311627/167998840-4db9b0c3-25c4-45b9-93e6-951f130ce446.png">

With justlight 2.1.2.3 this was solved better, the note was displayed directly after "Note:".

<img width="1199" alt="display_of_notes_V2 1" src="https://user-images.githubusercontent.com/16311627/167999131-9c53ca9a-cea9-4f45-a4f4-0dda65e7402c.png">

Thank you for your work and the great theme.

**Comment by JustCarmen** [comment]
This should already be solved with this commit: https://github.com/JustCarmen/webtrees-theme-justlight/commit/c758c5983cd459c88778c2584be8da7273b03678

The notes are very difficult to style. Perhaps you can test whether this solves your problem sufficiently.

**Comment by mpwt** [comment]
Thank you for the quick feedback and the code change that has already been made. After copying the changed file resources/views/theme/script.js.phtml it looks better, but there is still a line break after "Note:" or the note itself always starts on a new line.

<img width="1174" alt="notes_new" src="https://user-images.githubusercontent.com/16311627/168054743-04779c71-dbce-4522-abcc-e35b27297a85.png">

**Comment by mpwt** [comment]
The remaining line break seems to be a bug in webtrees. See https://github.com/fisharebest/webtrees/issues/4400.
