### ISSUE TITLE
Customize this page / Favorites: empty squares

### ISSUE THREAD

**Issue by ungeahnt** [JustCarmen/webtrees-theme-justlight#112]
I've some 'Favorites' that are not visible for visitors. With webtrees-theme these are completely suppressed.
With justlight-theme I see empty grey boxes. Shouldn't these boxes also be hidden?

![grafik](https://user-images.githubusercontent.com/28572767/168464007-83847651-fc9c-4d1a-ab06-58f20268f10a.png)

**Comment by JustCarmen** [comment]
This is not very easy. I only changed the layout and I don't control the code that determines if an entry is private or not.

I'll see what I can do.
