### ISSUE TITLE
v2.2.1 - Word breaks are incorrect with justlight theme

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/webtrees-theme-justlight#114]
Hi Carmen, please take a look at the word breaks Greg changed via CSS for .ut: 

https://github.com/fisharebest/webtrees/commit/de736bf7c624049e554db93a70ee45ea43d6bc79

Thank you.

**Comment by JustCarmen** [comment]
This is fixed in the yesterday release of webtrees and will be part of the next release of the Justlight theme.

Fix is here: https://github.com/JustCarmen/webtrees-theme-justlight/commit/07d9a5a544e87c46eaaa36abf3c2e960579e7815
