### ISSUE TITLE
Minor layout issue

### ISSUE THREAD

**Issue by WGroleau** [JustCarmen/webtrees-theme-justlight#117]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5910274/171518545-287ca2a8-dbbd-4647-b73b-aaf93dddde53.png">
Image results from:
<br/>
1 CENS<br/>
2 ADDR 641 Pine Street<br/>
3 CONT Medford, Oregon<br/>
2 SOUR @S141@<br/>
3 PAGE Oregon, Jackson Co., Medford, Ward 4, Sh. 82A<br/>
3 OBJE @M3231@<br/>
(Vesta modules also installed)

**Comment by mpwt** [comment]
This was also reported here: https://github.com/fisharebest/webtrees/issues/4353 if you mean the address formatting.

**Comment by WGroleau** [comment]
I use Safari on a MacOS laptop.  I have several two-line addresses in census records.  I never saw one like this until today.  Since I switched to the JustLight theme yesterday, I assumed it was in that theme, but apparently that is not the case.

**Comment by JustCarmen** [comment]
Since this is not an issue with the JustLight theme I will close this issue.
