### ISSUE TITLE
Error exception with webtrees 2.1.14

### ISSUE THREAD

**Issue by netinfoIT** [JustCarmen/webtrees-theme-justlight#128]
The theme is not loading with webtrees 2.1.14:
```
uasort(): Argument #2 ($callback) must be a valid callback, class Fisharebest\Webtrees\I18N does not have a method "strcasecmp" …\modules_v4\jc-theme-justlight\JustlightTheme.php:418
```

**Comment by LarsRabe** [comment]
No problem for me

**Comment by JustCarmen** [comment]
What version of the Justlight theme do you use? The reported error was fixed months ago.

I suggest to update the theme to the latest version.

**Comment by ChristopheSeg** [comment]
No problem for me with Webtrees 2.1.15 and webtrees-theme-justlight 2.2.4.

**Comment by netinfoIT** [comment]
I use webtree 2.1.14 and webtrees-theme-justlight 2.2.4.and webtrees 2.1.2.3. Trying to upgrade

**Comment by netinfoIT** [comment]
Hello, it is working well after upgrade. Thanks, my bad. Not sure why I didn't download the latest version first.

**Comment by netinfoIT** [comment]
Still OK on webtrees 2.1.15. Thanks.
