### ISSUE TITLE
Interactive Tree - Borders extend into sideblocks 

### ISSUE THREAD

**Issue by gudjonsi** [JustCarmen/webtrees-theme-justlight#130]
I noticed with version 2.1.5 of webtrees that the block for the individual interactive tree extends outside to the sideblocks, this only occurs for the theme JustLight (default webtrees themes are working ok), see enclosed image. This has been tested in Firefox, Vivaldi and Safari and this occurs in all of these browsers for the JustLight theme.

![Image 27 12 2022 at 17 43](https://user-images.githubusercontent.com/100283838/209703299-47c6c643-175f-4127-a6d3-5bf71a6332de.jpeg)

**Comment by JustCarmen** [comment]
This is already fixed with commit 40f9d5d830aefd6150e509e4fd68e7aec42a7a61. It will be added to the next release.

**Comment by gudjonsi** [comment]
Thanks for your support and a great theme.
