### ISSUE TITLE
Gap in footer lines

### ISSUE THREAD

**Issue by JustCarmen** [JustCarmen/webtrees-theme-justlight#132]
See: https://www.webtrees.net/index.php/en/forum/4-customising/37576-how-to-change-the-position-of-entries-in-the-footer#96689

**Comment by LarsRabe** [comment]
see also my answer to your questions in the forum

**Comment by LarsRabe** [comment]
Just for you info:
This is how it looks like now, including the 2 custom footer entries, on a Windows 10 computer:
![pc](https://user-images.githubusercontent.com/119816325/210174417-b899b1e7-9ae2-422f-b29c-ce3baee3fdfa.jpg)

And this is how it looks on a android pad 10,8 inch (landscaped):
![pad](https://user-images.githubusercontent.com/119816325/210174437-7f0d7791-7d08-4301-a295-01f014051949.jpg)

**Comment by JustCarmen** [comment]
I've solved the gap caused by changes made in webtrees: https://github.com/fisharebest/webtrees/commit/5712865df1d46841df931c4993e5c99943abdf90  caused it.

Furthermore I've improved the layout by aligning the items at the bottom.

Every footer section should have my-2 in stead of py-2 to be consistent in all themes. This also counts for custom footer items.

**Comment by LarsRabe** [comment]
Works now as intended. Aligning is also better this way.
![footer](https://user-images.githubusercontent.com/119816325/210256351-8310766c-d8b7-4e77-92e2-a6cfaf28dbae.jpg)
