### ISSUE TITLE
Places in wt 2.1.17 on small devices (or screen)

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-theme-justlight#145]
see 
https://github.com/jon48/webtrees-theme-rural/issues/62
and
https://github.com/fisharebest/webtrees/pull/4774

If you want, I can take screenshots with justlight theme.

**Comment by arbor95** [comment]
It seems as if the changes from https://github.com/fisharebest/webtrees/pull/4798 have to be implemented in your theme.

**Comment by arbor95** [comment]
Could you please fix this error please. I use the Places tab as the first tab and if there is no map it is really not nice. The error only shows up on mobile phones or on a correspondingly reduced window.

**Comment by arbor95** [comment]
you can see a working solution (fix) at another theme:
https://github.com/06Games/Webtrees-ArgonLight/commit/2ada337b201b3987ca024d1e3637bc269f2155ab

**Comment by JustCarmen** [comment]
Did you test it against the latest dev version or the stable release? Cause I think this is already implemented in the lates dev version. The dev code contains webtrees 2.1.17 css with a fixed height on the places map.

**Comment by arbor95** [comment]
I used 2.1.17 .

**Comment by arbor95** [comment]
With 2.2.6 the map is visible again in all cases. 
Moving complete screen may be a bit tricky in some cases.
I still like best the solution of the Argon Light theme, where the legend scrolls independant from the map. 
It is more intuitive for the user, if you want to scroll/move the complete screen.
