### ISSUE TITLE
Translated file in German / Übersetzte Datei auf deutsch (de.php)

### ISSUE THREAD

**Issue by Paderman** [JustCarmen/webtrees-theme-justlight#148]
Here's the translation in German 🙂
Extract _jc-theme-justlight.de.zip_ file, copy _de.php_ to _jc-theme-justlight/resources/lang/_

Hier ist die Übersetzung auf deutsch 🙂
Datei _jc-theme-justlight.de.zip_ entpacken, _de.php_ nach _jc-theme-justlight/resources/lang/_ kopieren

Download translated file / übersetzte Datei herunterladen:
[jc-theme-justlight.de.zip](https://github.com/JustCarmen/webtrees-theme-justlight/files/12101368/jc-theme-justlight.de.zip)

**Comment by JustCarmen** [comment]
Thank you!
