### ISSUE TITLE
Hamburger menu not working on mobile with webtrees version 2.1.7 and JustLight 2.2.2.1

### ISSUE THREAD

**Issue by gmarcon** [JustCarmen/webtrees-theme-justlight#149]
I just upgraded to webtrees version 2.1.7 (from 2.1.6) and the hamburger menu is not working anymore on the mobile version of the website. Clicking on the hamburger icon (navbar-toggler-icon) does not perform any action, while on webtrees 2.1.6 it worked (I tried a downgrade and I confirm that it is working with webtrees 2.1.6).

Module version: 2.2.2.1
Webtrees version: 2.1.7
Website: genealogy.marcon.tv (currently downgraded to 2.1.6, I can upgrade a copy of the website if needed to reproduce the bug)

Thank you for your support!

**Comment by gmarcon** [comment]
As an information: I can reproduce the issue also on Chrome Desktop emulating a mobile device with the Developer Tools.

**Comment by mpwt** [comment]
Test v2.2.5 of Justlight with you installed version of webtrees (v2.1.16). For webtrees v2.1.17 you should test Justlight v2.2.6. The correct version of Justlight you will find here: <https://github.com/JustCarmen/webtrees-theme-justlight/releases>.

**Comment by gmarcon** [comment]
Thank you, I confirm that with Justlight v2.2.6 and webtrees v.2.1.17 the menu works correctly on mobile!

Unfortunately I did not get a notification about a new version of the module being available (they usually show up in the control panel) and I did not think of checking it out, sorry!
