### ISSUE TITLE
Block borders in Justlight Palette

### ISSUE THREAD

**Issue by gudjonsi** [JustCarmen/webtrees-theme-justlight#150]
It would be nice to be able to enable block borders for the JustLight Palette of the JustLight Theme, same as is in place for the JustBlack Palette.

When switching between the JustLight and JustBlack Palettes the different layout of the Palettes causes different displaying of information and images i.e. specifically in the HTML Blocks which creates less symmetry between the Palettes in this respect. I would like to be able to see only the color change when switching between the Palettes.

I've managed to enable borders for wt-block in the CSS & JS Module for the JustLight Palette with the following code but it would be nice to have this as a feature in the Theme if possible:

`<style>
[dir] .jc-palette-justlight .wt-block{border:1px solid #e6e6e6;background:#fcfcfc} [dir] .jc-palette-justlight .wt-block .wt-block-header{padding:.75rem 1.25rem} [dir] .jc-palette-justlight .wt-block .wt-block-content{padding:.75rem 1.25rem} [dir] .jc-palette-justlight .wt-side-blocks{border:none} [dir] .jc-palette-justlight .wt-side-blocks>div:not(:last-child){border-bottom:1px solid #e6e6e6}
</style>`

See also example on my wt website [Sigurbjörg](https://www.sigurbjorg.is)

Regards Gudjon.

**Comment by JustCarmen** [comment]
Thanks for reporting this. I agree a consistent layout between palettes is preferable.
