### ISSUE TITLE
Justblack and Fanchart of Rico Sonntag

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-theme-justlight#154]
using the fanchart of Rico Sonntag ( https://github.com/magicsunday/webtrees-fan-chart/issues ) looks bad.
See:
https://wijzijnfamilie.nl/tree/wijzijnfamilie/webtrees-fan-chart/I27?generations=6&fanDegree=210&fontScale=100&hideEmptySegments=1&showColorGradients=1&showParentMarriageDates=1&innerArcs=3

**Comment by JustCarmen** [comment]
This problem was reported a while ago. Currently, I see nothing wrong with the fan chart when using the Justlight theme.

Does this problem still exist? If so, can you be more specific about what you think is going wrong?

**Comment by arbor95** [comment]
yes, it does, see attached screenshot
![2024-01-31 08_50_22-Fächerdiagramm von Jan Knegt](https://github.com/JustCarmen/webtrees-theme-justlight/assets/6124739/bd7bb418-1578-496d-9716-a72b9e1087db)

**Comment by JustCarmen** [comment]
Sorry, my mistake. I was looking at the wrong palette.

Problem is clear.
