### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by durangod** [JustCarmen/webtrees-theme-justlight#155]
Hello, i was curious if you had any plans to add a custom logo to your theme options?  If not, what is the easiest way to mod your theme to add a custom logo?

PS  i did search for the term logo in the closed issues and did not find anything. 

Thank you for your time.  :)

I did figure out this much... using custom css module 

`
.wt-header-wrapper .jc-header-content-start .wt-site-logo {
  display: block;
}

`

that does add the logo but it puts the Large text text next to the logo 

LOGO         Our Family Tree   

And the Title needs to go under the logo.   So for now i just did display none on the title

`
.wt-site-title {
   display: none;
}

`

**Comment by JustCarmen** [comment]
Hi, I think you need to add flex-column to the outer div, like this:

`.jc-header-content-start {
flex-direction: column!important;
}`
