### ISSUE TITLE
No scroll bars no map views

### ISSUE THREAD

**Issue by Phil9904** [JustCarmen/webtrees-theme-justlight#156]
When viewing a map view, the event list on the right, should probably have scroll bars when there is a long list, but the list just continues to extend down with the "Design: justcarmen.nl" credit appearing in the middle of the list.

**Comment by JustCarmen** [comment]
Hi, I cannot reproduce this. The map views should have scrollbars in case of a long list, for example [here ](https://wijzijnfamilie.nl/tree/wijzijnfamilie/individual/I3104/Henriette-Honig#tab-places)and [here](https://wijzijnfamilie.nl/tree/wijzijnfamilie/pedigree-map-4/I3104).

Can you give me an example to a page where it goes wrong?

**Comment by Phil9904** [comment]
I just downloaded and reloaded on my site your JustLight theme. That fixed
the problem. It must have been a corrupted file.
Thanks for your response.
Phil
