### ISSUE TITLE
Contrast in Just-Black

### ISSUE THREAD

**Issue by LarsRabe** [JustCarmen/webtrees-theme-justlight#161]
Hello Carmen, after a crash of my site und changing the provider, I've made a new setup for webtrees 2.1.20.
In the just-black palette the contrast is very low (see screenshot), both on MS Edge - Laptop as on Chrome - Android tablet . I can't rember that was the case earlier. What changed?

![contrast](https://github.com/JustCarmen/webtrees-theme-justlight/assets/119816325/07291f17-0736-4609-b252-89ea1070a61a)

**Comment by JustCarmen** [comment]
It has to do with changes in the bootstrap theme framework. I think I've solved it by using the bootstrap dark theme. This solves multiple issues with the JustBlack theme.
