### ISSUE TITLE
Black Palette - Stories page - list/table

### ISSUE THREAD

**Issue by gudjonsi** [JustCarmen/webtrees-theme-justlight#168]
When viewing the Stories Page (list/table) in webtrees with the Black Palette activated in the JustLight theme, every second line in the list/table is black and hard to distinguish clearly, see image.
webtrees 2.1.20 and JustLight theme 2.2.7

![webtrees-stories-justlight-theme-black](https://github.com/user-attachments/assets/c6f97953-9d87-4cde-9ab3-5b9c562ff63a)

**Comment by JustCarmen** [comment]
It has to do with changes in the bootstrap theme framework. I think I've solved it by using the bootstrap dark theme. This solves multiple issues with the JustBlack theme.
