### ISSUE TITLE
JustLight Theme version 2.2.8 update - JustLight palette displays strangely

### ISSUE THREAD

**Issue by gudjonsi** [JustCarmen/webtrees-theme-justlight#170]
Thanks for the great update to the JustLight Theme.

The JustLight palette displays strangely, see images enclosed. The JustBlack palette is as it should be without any problems but not the JustLight palette.

I've downloaded the zip file a couple of times from GithHub and likewise installed the theme in the module folder of webtrees without the problem being solved. The problem appears in all the browsers I've have tested, FireFox, Safari and Chrome.

When I download a zip file from the JustLight Theme Main Code in GitHub and install it in the module folder of webtrees the problem is not present, everything appears normal. This problem can also be seen on the wijzijnfamilie.nl website.

Thanks.

![JustLight-Theme-JustBlack-Palette](https://github.com/user-attachments/assets/b3f454fb-0ac9-4e28-9a1a-5da6f509474f)
![JustLight-Theme-JustLight-Palette](https://github.com/user-attachments/assets/b8e36021-0649-4eaa-8aab-ef3b89127b85)

**Comment by gudjonsi** [comment]
More images, mobile view display problem.
![JustLight-Theme-JustBlack-Palette-3](https://github.com/user-attachments/assets/b3fb7d42-1ec6-4c2b-a1f0-9e9e9c3ee281)
![JustLight-Theme-JustLight-Palette-3](https://github.com/user-attachments/assets/76a9574a-091d-41fc-9b25-7b3ad0f306ea)

**Comment by JustCarmen** [comment]
I can reproduce your issue. It seems like sometimes, the JustLight theme still is in dark mode while it shouldn't when switching to that palette. I'll look into this.
