### ISSUE TITLE
JustLight Theme Update 2.2.8 - Customize page - Display problem.

### ISSUE THREAD

**Issue by gudjonsi** [JustCarmen/webtrees-theme-justlight#171]
The display problem in the JustLight Theme update 2.2.8 also appear when selecting the action "Customize Page", but differently, see images for both JustLight Palette and JustBlack Palette.

![JustLight-Theme-JustLight-Palette-2](https://github.com/user-attachments/assets/d8e7a88c-9718-4c7e-96d5-fc3ea21b0095)
![JustLight-Theme-JustBlack-Palette-2](https://github.com/user-attachments/assets/bd84522c-e623-4a45-8a29-dae1da112e64)

**Comment by JustCarmen** [comment]
Thanks for reporting. This doesn't look good indeed. I'll fix this.

**Comment by arbor95** [comment]
see also
https://www.webtrees.net/index.php/forum/4-customising/39238-justlight-theme-justblack-colors-problem#107085
