### ISSUE TITLE
Family navigator partly unreadable

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-theme-justlight#172]
see
https://www.webtrees.net/index.php/forum/4-customising/39238-justlight-theme-justblack-colors-problem#107085

**Comment by JustCarmen** [comment]
Hello, I released a new version earlier this week that fixes this problem. Do you use the latest version?

**Comment by arbor95** [comment]
Yes, as written in linked forum thread.

**Comment by JustCarmen** [comment]
Sorry, but I cannot reproduce this. It looks good to me.

https://wijzijnfamilie.nl/tree/wijzijnfamilie/individual/I940/Leendert-Leo-Knegt

**Comment by arbor95** [comment]
with version justlight-2.2.8.1 the error has gone (and the my page edit too), thx
