### ISSUE TITLE
justlight-2.2.8 - Runtime exception - Missing file

### ISSUE THREAD

**Issue by webtrees-pesz** [JustCarmen/webtrees-theme-justlight#173]
RuntimeException: View file not found: /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/modules_v4/jc-theme-justlight/resources/views/layouts/body/navbar-toggler.phtml in /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/View.php:260
Stack trace:
#0 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/View.php(183): Fisharebest\Webtrees\View->getFilenameForView()
#1 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/View.php(278): Fisharebest\Webtrees\View->render()
#2 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#3 /var/www/vhosts/utischill.genonline.de/httpdocs/webtrees/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/defaultJustLight.phtml(75): view()

**File navbar-toggler.phtml is not part of justlight-2.2.8.zip\jc-theme-justlight\resources\views\layouts\body**

![image](https://github.com/user-attachments/assets/48a31fd1-b3b6-44b4-84ae-efa8f5aa3021)

**Comment by JustCarmen** [comment]
This looks like an issue with Vesta. In this version of the theme I've split up the cellphone menu into two separate menus. The primary (genealogy) and the secondary (user) menu. The file navbar-toggler doesn't exist anymore in this version. You should raise an issue at https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues

**Comment by webtrees-pesz** [comment]
Hello Carmen,

thanks a lot for the super-fast response.

Best regards, Peter
