### ISSUE TITLE
compatibility with WT 2.2

### ISSUE THREAD

**Issue by eliseur** [JustCarmen/webtrees-theme-justlight#180]
Hello,

Can you make your theme compatible with webtrees 2.2 ? 

Thank you.

**Comment by arbor95** [comment]
+1

**Comment by JustCarmen** [comment]
There is a new 2.2. compatible release available.

https://github.com/JustCarmen/webtrees-theme-justlight/releases/tag/2.3.0

**Comment by eliseur** [comment]
Thank you.
I opted for emotions lite.

Olivier
________________________________
