### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by SodanWT** [JustCarmen/webtrees-theme-justlight#183]
Hi Carmen,

I don't know how to create a proper pull request, so I give you here the french translation I made for your great theme that I use since several years.

```
return [
    'Default color palette' => 'Palette de couleurs par défaut',
    'Select “JustAuto” to automatically choose the JustLight or JustBlack palette depending on the Windows color mode.' =>
    'Sélectionnez “JustAuto” pour choisir automatiquement la palette JustLight ou JustBlack selon le mode de couleur de Windows.',
    'Allow visitors to switch to another color palette' => 'Permettre aux visiteurs de changer de palette de couleurs',
    'Automatically chooses a palette based on Windows color mode' => 'Choix de palette automatique selon le mode de couleur de Windows'
];
```

Doing so I have 2 remarks:
1) It is said that "JustAuto" applies depending on the Windows color mode, but I think it is depending on the browser color mode. So I made another translation that will be valid if you change "Windows" to "browser".
2) The translation of the color scheme "JustLight" has a side effect, as it also change the name of your module in the title of your module, and in the list of installed modules. So in JustlightTheme.php I changed the name of the schemes so they can be easily translated and your module keep its name:
    'JustAuto' => 'Auto'
    'JustLight' => 'Light',
    'JustBlack' => 'Black'

With these 2 remarks, my final translation file fr.php is:

```
return [
    'Default color palette' => 'Palette de couleurs par défaut',
    'Select “Auto” to automatically choose the Light or Black palette depending on the browser color mode.' =>
    'Sélectionnez “Automatique” pour choisir automatiquement la palette Claire ou Sombre selon le mode de couleur du navigateur.',
    'Allow visitors to switch to another color palette' => 'Permettre aux visiteurs de changer de palette de couleurs',
    'Automatically chooses a palette based on browser color mode' => 'Choix de palette automatique selon le mode de couleur du navigateur',
    'Auto' => 'Automatique',
    'Light' => 'Claire',
    'Black' => 'Sombre'
];
```

Thank you for your work

**Comment by JustCarmen** [comment]
In fact you're raising multiple issues here:
1. A new French translation
2. Detection of the color mode is based on the browser in stead of on Windows.
3. The naming of the palettes.

1 and 2 are solved. You were right, de detection of the color mode is based on the browser (which might be derived from the device, but that is not necessarily Windows).

3. Naming the palettes is on my to-do list, but I want to do that later. I also want to separate the foreground colors from the background colors so we can have a dark or light background with different foreground colors. When that is completed the palettes will be renamed. I will create a separate issue for this.
