### ISSUE TITLE
Large markdown table crashes layout

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/webtrees-theme-justlight#32]
When I have a large markdown table (created with census assistant) the layout crashes.

Is there a css solution? With other webtrees themes the table is horizontal scrollable and the page layout stops on the right side.

<img width="1279" alt="markdown_table" src="https://user-images.githubusercontent.com/16311627/40626387-850408d2-62b8-11e8-815e-840935fd5320.png">

**Comment by mpwt** [comment]
#fisharebest/webtrees/issues/1427

**Comment by JustCarmen** [comment]
I am not able to fix this. When the table gets to large and we cannot truncate text anymore then it should be split up in smaller parts. This issue should be fixed by webtrees.
