### ISSUE TITLE
Feature Request: privacy policy

### ISSUE THREAD

**Issue by MichielB79** [JustCarmen/webtrees-theme-justlight#33]
Ik zag op jouw eigen webtrees site een mooi privacy verklaring. Ik zou dat graag op dezelfde wijze willen doen. Is het mogelijk dit te integreren in het justlight thema?
Ik heb dit ook via het contactformulier via jouw website gevraagd, maar betwijfel of dit goed gegaan is.

Bij voorbaat dank!
Michiel

**Comment by JustCarmen** [comment]
Sorry voor deze late reactie, maar ik heb besloten om de privacy verklaring niet te integreren in het JustLight thema. Ik ben op dit moment ook niet van plan om deze als aparte module uit te geven. Ik heb mijn eigen privacy verklaring inmiddels wel aangepast voor gebruik met webtrees 2. Als je nog steeds geïnteresseerd bent, kan ik je de bestanden mailen. Deze kun je dan zelf naar wens aanpassen en op je site plaatsen.
