### ISSUE TITLE
Unable to install/upgrade via Git

### ISSUE THREAD

**Issue by martignoni** [JustCarmen/webtrees-theme-justlight#34]
Older versions of JustLight theme were installable and upgradable via Git, which was very quick and handy for power users.

Unfortunately this is not possible anymore. Is it possible to allow such workflow available again?

**Comment by JustCarmen** [comment]
The Git workflow has been repaired. The JustLight theme for webtrees 2 has been released today.

**Comment by martignoni** [comment]
Thanks, much appreciated.
