### ISSUE TITLE
How to install dev version of the team to webtrees 2.0?

### ISSUE THREAD

**Issue by deeptowncitizen** [JustCarmen/webtrees-theme-justlight#36]
The team is not recognized by 2.0 from root, `themes`, modules folders.

**Comment by janobarnard** [comment]
I also can't get justlight to be recognised by version 2.0.3 of webtrees. It's really sad as it was a great-looking theme and much better than the default options.

**Comment by JustCarmen** [comment]
With some delay, the JustLight theme for webtrees 2 has been released today.
