### ISSUE TITLE
Panels as tabs

### ISSUE THREAD

**Issue by adelatour11** [JustCarmen/webtrees-theme-justlight#40]
Hi , thank you for this wonderful theme
I would like to know if it is possible to have panels as tabs in the individual pages just like in the justblack theme ?

Would it be possible to change a piece of code of the justlight theme from the justblack theme just to replace panels by tabs ?

Thanks

**Comment by JustCarmen** [comment]
Today I've released the JustLight theme for webtrees 2 which has tabs in stead of panels.
