### ISSUE TITLE
justlight not recognised by webtrees v2.0.3

### ISSUE THREAD

**Issue by janobarnard** [JustCarmen/webtrees-theme-justlight#41]
I can't get justlight to be recognised by version 2.0.3 of webtrees. I understand that the structure of webtrees 2 changed a bit and as a result the theme would need to be slightly modified. Would this be possible? It would be really sad if justlight development ends as it was a great-looking theme and much better than the default themes.

**Comment by spikerguy** [comment]
I tried on the latest webtree v2 and it doesn't seem to recognize it

Any plan on upgrading the module? @JustCarmen

**Comment by JustCarmen** [comment]
Hi guys,

I am sorry for the late response but due to personal circumstances I wasn't able to update my themes and modules any sooner.

I just want to let you know that I am working on the JustLight theme. If nothing happens in between I think I could have a first version ready within a few weeks. I haven't commit anything yet because it is still in pre-development state but I am making progress.

**Comment by fhiernaux** [comment]
Any news about the updated theme for version 2?

**Comment by spikerguy** [comment]
Hi @JustCarmen,
It is good to see you back. No rush take your time, if you need help in testing then feel free to tag me here.



> Any news about the updated theme for version 2?
Yes you can follow the updates on the V2 branch [Here](https://github.com/JustCarmen/justlight/tree/feature/wt-2)

**Comment by JustCarmen** [comment]
I've just released the JustLight theme for webtrees 2.

**Comment by f-9t9it** [comment]
Thanks for the hard work.

**Comment by spikerguy** [comment]
Thanks for the hard work.

UPDATE: Just tested and it worked flawlessly.

**Comment by fhiernaux** [comment]
I just try it now and seems to work well with webtrees 2.0.7 ; thanks a lot for this updated theme.

**Comment by JustCarmen** [comment]
> @JustCarmen Do you plan to update fancy treeview module ?

Yes eventually, but it will take some time. It is on the list but not my first priority.
