### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-theme-justlight#45]
After installation and first selection of this new webtrees 2 theme, I got an error:
`
ErrorException: filemtime(): stat failed for /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/webtrees-theme-justlight/resources/css/justlight.min.css in /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Module/ModuleCustomTrait.php:146 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'filemtime(): st...', '/mnt/web312/a3/...', 146, Array) #1 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Module/ModuleCustomTrait.php(146): filemtime('/mnt/web312/a3/...') #2 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/webtrees-theme-justlight/module.php(104): class@anonymous->assetUrl('css/justlight.m...') #3 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/webtrees-theme-justlight/resources/views/layouts/default.phtml(69): class@anonymous->stylesheets() #4 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/View.php(189): include('/mnt/web312/a3/...') #5 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/View.php(286): Fisharebest\Webtrees\View->render() #6 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('layouts/default', Array) #7 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/ViewResponseTrait.php(58): view('layouts/default', Array) #8 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/RequestHandlers/UserPage.php(91): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->viewResponse('user-page', Array) #9 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->handle(Object(Nyholm\Psr7\ServerRequest)) #10 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/vesta_classic_look_and_feel/ClassicLAFModule.php(146): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #12 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ClassicLAF\ClassicLAFModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #14 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(212): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/AuthMember.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #20 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthMember->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #21 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #23 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/Router.php(134): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #25 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #29
...
`

**Comment by mpwt** [comment]
Do you use the official release or the master code? I saw this error message too when I clone the master code to my test installation. Test to upload the release code (folder jc-themes-justlight). That works for me.

**Comment by JustCarmen** [comment]
Yes, please confirm the stable release does not produce this error message.

If you are using the master code you need to produce the stylesheet yourself by running 'npm run webtrees' and 'npm run development'. See https://github.com/JustCarmen/webtrees-theme-justlight#development. Have you done that?

**Comment by hartenthaler** [comment]
Ok, I see. I used the latest master code. Now I uploaded the stable release - it works fine! Thank you so much!

**Comment by JustCarmen** [comment]
Yw, Enjoy your theme :).
