### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-theme-justlight#48]
Hi Carmen,
the formatting is lost in the notes, i. e. the "end of line".
Please have a look at the note in 
https://www.heiler-ahnen.de/webtrees/tree/heiler/individual/I0160/Theodor-Heiler#tab-notes.
Kind regards
Jürgen Heiler

**Comment by JustCarmen** [comment]
Hi Jurgen,

Please provide a link to a non private note, because this note is not viewable for visitors.

I don't see any issues regarding layout in the note tab on my own site so I can't guess what the problem might be,

**Comment by mpwt** [comment]
Hi Carmen,
the indicated link also works as guest. The difference in the display is visible when switching to another theme. With Justlight the note is displayed without line breaks.

**Comment by JustCarmen** [comment]
When clicking on the link I see this:

![image](https://user-images.githubusercontent.com/5641963/92334531-292c9a80-f08f-11ea-803f-ac0d6176ba9b.png)

No visible note. Same when switching to the webtrees theme.

**Comment by mpwt** [comment]
With webtrees theme:
![8E5B5623-963E-4D65-8399-FC390E8BEB03](https://user-images.githubusercontent.com/16311627/92349956-dc20e680-f0d7-11ea-98da-7bf8f7cdbff6.jpeg)

With justlight theme:
![B028D19F-232D-4309-83BF-9E790596E014](https://user-images.githubusercontent.com/16311627/92349960-df1bd700-f0d7-11ea-8475-22c4be919c15.jpeg)
