### ISSUE TITLE
Stories tab in personal facts

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-theme-justlight#50]
Hi,
to my understanding the tab should be highlighted in blue if chosen or in grey, if not chosen but a story exists, or in white, if not chosen and no story exists. At this point the tab is always highlighted in white. Could you please check this.
Kind regards
Jürgen
heiler-ahnen.de

**Comment by JustCarmen** [comment]
This was a problem in webtrees core which has been solved recently.

See: https://github.com/fisharebest/webtrees/pull/3501
