### ISSUE TITLE
Long lists have page footer in the middle of the page

### ISSUE THREAD

**Issue by BertKoor** [JustCarmen/webtrees-theme-justlight#51]
Viewing someone elses webtrees site with your theme, I found that a long "branches" list has the page footer right in the middle of the list. Just scroll down here:
http://originofthekirbys.com/tree/Origins/branches/Kirby

Thank you!!

**Comment by mpwt** [comment]
Maybe this fix helps: https://github.com/JustCarmen/webtrees-theme-justlight/commit/499b48768c0279fc6b217bf9e042c67935d76fb3

**Comment by JustCarmen** [comment]
Mpwt is right. This fix should solve the issue.

I've just released version [2.0.7.1](https://github.com/JustCarmen/webtrees-theme-justlight/releases/tag/2.0.7.1) which contains the fix.
