### ISSUE TITLE
interactive tree: tree-page-block shows old wt-design (wt 2.0.9)

### ISSUE THREAD

**Issue by ungeahnt** [JustCarmen/webtrees-theme-justlight#60]
When I open the interactive tree via "Charts->Interactive tree" I see the "JustLight-Theme-layout" and I'm happy ;)

But if I add an interactive tree via "Customize this page"->Charts -> Interactive tree" then this block is still in the old wt-theme.

Is this intended?

**Comment by JustCarmen** [comment]
No, that is certainly not intended. I just forgot to style this part!
