### ISSUE TITLE
Missing icons in v2.0.9

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/webtrees-theme-justlight#66]
I found some missing icons in the current version:
- in /admin/modules -> wt-icon-individual
- in /admin -> wt-icon-add and also wt-icon-individual
- in /branches -> icon-rings (marriage symbol)

You can take a look at it and check it out. Thanks a lot.

**Comment by JustCarmen** [comment]
I've solved the rings icon but I cannot solve the missing admin icons because those are caused due to a bug in webtrees

https://github.com/fisharebest/webtrees/issues/3493

**Comment by mpwt** [comment]
Thank you. 

Are you planning to release a new version? Since version 2.0.9 some corrections have been made and it is not so easy to compare the master with the official version.

**Comment by JustCarmen** [comment]
Yes I am. There are a few remaining issues which I want to try to solve first, but without any distraction I expect to release within a week from now.

**Comment by JustCarmen** [comment]
I found a way to keep the original webtrees icons in admin and have the customized icons in front.

**Comment by mpwt** [comment]
Do you plan to release a new version?
