### ISSUE TITLE
Menu at mobile view is too simple 

### ISSUE THREAD

**Issue by mrqd9** [JustCarmen/webtrees-theme-justlight#69]
Primary and secondary menus should be separated in mobile screen with an active search bar.

I would like to suggest my idea that I wanted to make

Concept expanded hamburger
![IMG_20210105_020716](https://user-images.githubusercontent.com/56225476/103577906-a102b880-4efb-11eb-922c-78fb9c32e632.jpg)

Current expanded hamburger
![IMG_20210105_020945](https://user-images.githubusercontent.com/56225476/103578065-ed4df880-4efb-11eb-8f4e-0918b2296659.jpg)

**Comment by JustCarmen** [comment]
This is by design. It is my intention to keep the mobile menu simple. There is not much screen space to place the collapsible buttons and/or a searchbar on top. It soon gets messy. I don't see why these menu items can't be at the bottom. It gives a much cleaner layout.

**Comment by JustCarmen** [comment]
I partly meet your wishes by giving the search bar a more prominent place on mobile view. 

I will leave the secondary menu in place.
