### ISSUE TITLE
Meta Tags

### ISSUE THREAD

**Issue by heiler** [JustCarmen/webtrees-theme-justlight#70]
It seems to me that Meta tags are changed when using this theme. I see "<meta name="robots" content="index,follow">" using standard themes, instead "<meta name="robots" content="noindex">" using this theme. If I am right this would be a real show-stopper for me, because my page is not visible in the search engines.

**Comment by JustCarmen** [comment]
This is a bug. Some variable settings are missing.

Also discussed in the forum: https://www.webtrees.net/index.php/en/forum/4-customising/34995-vytux-pages-and-webtrees-2#82421
