### ISSUE TITLE
Small code error in statistics.phtml

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/webtrees-theme-justlight#71]
Line 161
`(<?= e($stats->largestFamilySize()) ?>&nbsp;<?= strtolower(I18N::translate('Children')) ?>)`
should be
`(<?= e($stats->largestFamilySize()) ?>&nbsp;<?= I18N::translate('Children') ?>)`

F.i. in German "Children" are "Kinder" and not "kinder". Thank you.

**Comment by JustCarmen** [comment]
I see what you mean. This is not correct. I need to use %s child/%s children to solve this.

https://translate.webtrees.net/translate/webtrees/webtrees/de/?q=%25s+child&type=all&offset=2

**Comment by mpwt** [comment]
Ok, even though a single child should be rare in the family with most children.

**Comment by JustCarmen** [comment]
True. But the JustLight theme normally don't need to translate anything. Only in this particular case. Therefore it uses translatable strings from mainstream webtrees only. Of course the outcome will always be %s children.
