### ISSUE TITLE
New release for webtrees v2.0.12/13?

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/webtrees-theme-justlight#75]
Are you planning a new release for webtrees v2.0.12/13 in the near future? The changes to the map icons I also wanted to ask ... Thank you.

**Comment by JustCarmen** [comment]
The JustLight theme works just fine in v2.0.12/13 without any adjustments, so I don't know what you mean.

I am planning a new release though, because I did some changes. So can you please tell me which icons you miss? Maybe I can fix it before the new release.

**Comment by mpwt** [comment]
I saw that you made changes and i have limited ability to compile the code myself. That's why I asking ...

![EB46A539-CAA1-4F30-A6E0-953EDDA96F78](https://user-images.githubusercontent.com/16311627/111321665-71dd9580-8668-11eb-9cce-2aea82f2e42d.jpeg)

Thank you very much for the nice theme!

**Comment by JustCarmen** [comment]
Ah, I see. I guess I was sleeping this morning... But it is your lucky day. Already solved: https://github.com/JustCarmen/webtrees-theme-justlight/commit/5dbe949c57ff4da465f7f73603a10fdb6323293b

I will bring out a new release later this week.
