### ISSUE TITLE
config not posible

### ISSUE THREAD

**Issue by arbor95** [JustCarmen/webtrees-theme-justlight#89]
Theme version 2.1.0
clicking on the wrench gives error:
Namespace "_jc-theme-justlight_" not found. …/app/View.php:260
#0 …/app/View.php(189): Fisharebest\Webtrees\View->getFilenameForView()
#1 …/app/View.php(286): Fisharebest\Webtrees\View->render()
#2 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make()
...

**Comment by mpwt** [comment]
Sure? On my website I have no error message when using the settings.

Did you replace the complete module folder? I added ".disable" to the old one and upload the new one. So far it works.

Thanks to Carmen for the new version.

**Comment by arbor95** [comment]
I found the reason: Default I have another Theme (the Rural).
If that is switched on, I get the error.
Switching to JC Theme, configuration works.
On error: Console says:
Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at Asset?asset=js%2Fscript.js&hash=1577685323:1
(anonymous) @ Asset?asset=js%2Fscript.js&hash=1577685323:1
