### ISSUE TITLE
sidebar elements are not ok

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-theme-justlight#90]
Most of the elements are looking great! Super!

But the elements in the sidebar on the right side are gray on white. Is this may be a side effect by one of the custom modules I have installed?
![Screenshot (464)](https://user-images.githubusercontent.com/6324175/132045636-d43e0755-9400-4162-885f-682932477b6f.png)

**Comment by JustCarmen** [comment]
Hi Hermann, I cannot reproduce this. I see you are using Vesta modules. Is there a Vesta module interfering with the sidebar?

**Comment by hartenthaler** [comment]
I have all the modules installed ;-)

It was the module "Theme modifications" / [custom-css](https://github.com/makitso/custom-css/issues) from Rob Peters. I raised an issue on his page.

**Comment by makitso** [comment]
If you can give me a link to your site and page I can look at the problem.

**Comment by makitso** [comment]
There was a custom.css regression in the changes for Bootstrap 5, I have released a new version.

**Comment by JustCarmen** [comment]
Great. Thanks Rob for the quick fix.
