### ISSUE TITLE
I put this poster in the upper left corner

### ISSUE THREAD

**Issue by yako1984** [JustCarmen/webtrees-theme-justlight#91]
Every time I refresh or load a page, I put this poster in the upper left corner, with the new update.
a greeting

![contenido](https://user-images.githubusercontent.com/67491705/133257892-f8547eea-520e-41f4-b7ba-9f9b31a59aa1.png)

**Comment by mpwt** [comment]
Are you planning to release a new version? In the past, the master code could be used directly, but I can't use the current solution with Composer and npm.

**Comment by JustCarmen** [comment]
You don't need the whole development package to just take advantage of this change. In this case it is enough to update the css files in the resources folder.
