### ISSUE TITLE
Missing files in default Webtrees 2.x install cause theme to fail

### ISSUE THREAD

**Issue by tdack** [JustCarmen/webtrees-theme-justlight#95]
The following files are not present in a default Webtrees 2.x install and cause the theme to fail

```
/public/favicon-196.png
/public/browserconfig.xml
/public/site.webmanifest
```
Creating empty files results in the theme rendering correctly.

Truncated error message:
```
ErrorException: filemtime(): stat failed for /var/www/family.dack.com.au/app/../public/browserconfig.xml in /var/www/family.dack.com.au/app/Helpers/functions.php:62
Stack trace:
#0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 /var/www/family.dack.com.au/app/Helpers/functions.php(62): filemtime()
#2 /var/www/family.dack.com.au/modules_v4/jc-theme-justlight/resources/views/layouts/default.phtml(65): asset()
```

**Comment by JustCarmen** [comment]
These files are removed in webtrees 2.1. which is currently in alpha status. This theme does not work with webtrees 2.1-alpha. It works with the latest stable version of webtrees, (2.0.19 at the moment).

My experience is that code changes a lot during development for a major release, so I will most likely not update the theme to webtrees 2.1. alpha or beta versions.

**Comment by AlphaJack** [comment]
Thank you for the clarification
